import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>webuycheap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="landingPageContent" className="landingPage">
        <Image id="unboxingImage" className="unboxingImage" src="/images/unboxing.jpeg" alt="Person unboxing new item" width="1000" height="703" />
        <div id="landingPageTitleItem">
          <ul id="landingPageTitleList">
            <li>we.</li>
            <li>buy.</li>
            <li>cheap.</li>
          </ul>

          <a id="landingPageProductButton" className="cta-button" href="/products">explore products</a>
        </div>
      </main>
    </div>
  )
}

export default Home
